# Generated by Django 5.2.8 on 2025-12-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_at',
            new_name='created_at',
        ),
    ]
